### ISSUE TITLE
Mvn install do not work from command line but it works in Eclipse

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.simulator.external#11]
NeuronSimulatorServiceTest doesn't pass because:
```
No matching bean of type [org.geppetto.simulator.external.services.NeuronSimulatorService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency.
```

Looks like sth related to SpringJUnit4ClassRunner, maybe it goes in this [sense](http://stackoverflow.com/questions/3365628/junit-tests-pass-in-eclipse-but-fail-in-maven-surefire). However the error stacktrace is different than the one mentioned in the link. I don't know if it is exactly the same error...

I have tried updating junit lib version, changing from spring junit to junit, updating  maven-surefire-plugin lib version and setting different parameters... No succeed so far.

**Comment by tarelli** [comment]
@adrianq @jrmartin I just spent 2 hours on this, still no success. We basically need to make the test aware of the bean for the simulator that I suspect is not being found since it is inside the osgi-config rather than in the app-config which the test knows about. Said so I spent two hours trying to do this to no avail, even if I add stuff it seems to not find it, to the extent that I added another test-config file to the same folder where app-config is and maven complains FileNotFound.
